# config/packages/knp_gaufrette.yaml
knp_gaufrette:
    adapters:
        userfiles:
            local:
                directory: /var/www/html/files/users

        usergroupfiles:
            local:
                directory: /var/www/html/files/groups

    filesystems:
        userfiles:
            adapter:    userfiles

        usergroupfiles:
            adapter:    usergroupfiles

    stream_wrapper: ~
