# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    loaders:
        userfiles:
            stream:
                wrapper: gaufrette://userfiles/
        usergroupfiles:
            stream:
                wrapper: gaufrette://usergroupfiles/
    filter_sets:
        avatar:
            data_loader: userfiles
            cache: ~
            quality: 75
            filters:
                thumbnail: { size: [52, 52], mode: outbound }
        profile:
            data_loader: userfiles
            cache: ~
            quality: 75
            filters:
                thumbnail: { size: [150, 150], mode: outbound }
